#!/bin/bash
##################################################################################################




##################################################################################################
EXT_REC_NPK_HASH_VALUE='HASH(A.BD,A.BATCH_ID,A.SUPER_BATCH_ID,A.CLIENT_ID,A.ACCT_ID,A.SPON_CODE,A.SPONSOR_ACCT_NUMBER,A.PROD_SPON_CODE,A.PRODUCT_NUMBER,A.ACTUAL_CUSIP,A.PRODUCT_NAME,A.PRODUCT_SHORT_NAME,A.CONFIRM_NUMBER,A.TRADE_DATE,A.CANCEL_DATE,A.RECEIVE_DATE,A.SETTLEMENT_DATE,A.STATE_CODE,A.INVESTMENT_AMT,A.GDC_AMT,A.NET_CONCESSION_AMT,A.FEE_ID,A.FEE_AMT,A.FEE_EXEMPT_IND,A.INCOMING_FEE_AMT,A.UNITS,A.UNITS_PRICE,A.TRADE_SOURCE_IND,A.ELECTRONIC_TRADE_IND,A.NAV_IND,A.A12B1_IND,A.GDC_CREDIT_ONLY_IND,A.PRINCIPAL_IND,A.BUY_SELL_IND,A.HELD_IND,A.HELD_REASON,A.RDS_OVERRIDE_IND,A.SPLIT_IND,A.POST_DATE,A.POST_IND,A.RELATED_TRADE_ID,A.NOTES,A.CREATE_ID,A.CREATE_DATE,A.LAST_MOD_ID,A.LAST_MOD_DATE,A.SEC_TYPE,A.SEC_MOD,A.BLOTTER_CODE,A.MARKET_CODE,A.SS_CODE,A.FEE_CODE,A.FEE_OVERRIDE_IND,A.TOTAL_ORDER_UNITS,A.MANUAL_HELD_IND,A.TYPE_OF_ORDER,A.PROD_TYPE_CODE,A.TRAIL_FREQ_IND,A.HELD_REASON_CODE,A.MARKET_PRIMARY_IND,A.PRIMARY_EXCHANGE,A.PD_DATE,A.RNR,A.COMMISSIONBASISREASON,A.COMMISSIONBASISAMOUNT,A.COMMISSIONRATE)'

OPT_TABLE_COLS='A.TRADE_ID,A.BD,A.BATCH_ID,A.SUPER_BATCH_ID,A.CLIENT_ID,A.ACCT_ID,A.SPON_CODE,A.SPONSOR_ACCT_NUMBER,A.PROD_SPON_CODE,A.PRODUCT_NUMBER,A.ACTUAL_CUSIP,A.PRODUCT_NAME,A.PRODUCT_SHORT_NAME,A.CONFIRM_NUMBER,A.TRADE_DATE,A.CANCEL_DATE,A.RECEIVE_DATE,A.SETTLEMENT_DATE,A.STATE_CODE,A.INVESTMENT_AMT,A.GDC_AMT,A.NET_CONCESSION_AMT,A.FEE_ID,A.FEE_AMT,A.FEE_EXEMPT_IND,A.INCOMING_FEE_AMT,A.UNITS,A.UNITS_PRICE,A.TRADE_SOURCE_IND,A.ELECTRONIC_TRADE_IND,A.NAV_IND,A.A12B1_IND,A.GDC_CREDIT_ONLY_IND,A.PRINCIPAL_IND,A.BUY_SELL_IND,A.HELD_IND,A.HELD_REASON,A.RDS_OVERRIDE_IND,A.SPLIT_IND,A.POST_DATE,A.POST_IND,A.RELATED_TRADE_ID,A.NOTES,A.CREATE_ID,A.CREATE_DATE,A.LAST_MOD_ID,A.LAST_MOD_DATE,A.SEC_TYPE,A.SEC_MOD,A.BLOTTER_CODE,A.MARKET_CODE,A.SS_CODE,A.FEE_CODE,A.FEE_OVERRIDE_IND,A.TOTAL_ORDER_UNITS,A.MANUAL_HELD_IND,A.TYPE_OF_ORDER,A.PROD_TYPE_CODE,A.TRAIL_FREQ_IND,A.HELD_REASON_CODE,A.MARKET_PRIMARY_IND,A.PRIMARY_EXCHANGE,A.PD_DATE,A.RNR,A.COMMISSIONBASISREASON,A.COMMISSIONBASISAMOUNT,A.COMMISSIONRATE,A.REC_NPK_HASH_VALUE,A.INSERT_LOAD_TS,A.LOAD_USR,A.LST_UPDATE_TS,A.LST_UPDATE_USR'

#sudo -su hdfs hive -e "SELECT A.* ,${EXT_REC_NPK_HASH_VALUE} ,CURRENT_TIMESTAMP AS INSERT_LOAD_TS ,'' AS LOAD_USR ,'NULL' AS LST_UPDATE_TS ,'' AS LST_UPDATE_USR ,'NULL' AS LST_DELETE_TS ,'' AS LST_DELETE_USR FROM BONUS.EXT_TRADES A LEFT JOIN BONUS.OPT_TRADES B ON A.TRADE_ID=B.TRADE_ID WHERE B.TRADE_ID IS NULL ; "


# UNION ALL SELECT A.* ,${EXT_REC_NPK_HASH_VALUE} ,'null' INSERT_LOAD_TS ,'' AS LOAD_USR ,current_timestamp AS LST_UPDATE_TS ,'' AS LST_UPDATE_USR ,'NULL' AS LST_DELETE_TS ,'' AS LST_DELETE_USR FROM BONUS.EXT_TRADES A JOIN BONUS.OPT_TRADES B ON A.TRADE_ID=B.TRADE_ID WHERE ${EXT_REC_NPK_HASH_VALUE} <> B.REC_NPK_HASH_VALUE SELECT ${OPT_TABLE_COLS} ,current_timestamp AS LST_DELETE_TS ,'' AS LST_DELETE_USR FROM BONUS.OPT_TRADES A LEFT JOIN BONUS.EXT_TRADES B ON A.TRADE_ID=B.TRADE_ID WHERE B.TRADE_ID IS NULL;"

sudo -su hdfs hive -f "/home/splice/cetera/sqoop/BONUS/bonus_avro_hive.hql"  --hiveconf EXT_REC_NPK_HASH_VALUE=${EXT_REC_NPK_HASH_VALUE} --hiveconf OPT_TABLE_COLS=${OPT_TABLE_COLS}
